name: primer_impacto
version: '1.0.0'
config-version: 2

profile: primer_impacto

model-paths: ["models"]

models:
  primer_impacto:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table